version: '3.8'

services:
  info-table:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: info-table
    ports:
      - 3000:3000
    command: [ "yarn", "start" ]
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
