version: '3.8'

services:
  info-table:
    image: ndkv9/infotable
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: info-table
    ports:
      - 3000:3000
    command: [ "yarn", "start" ]
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

volumes:
  node_modules:
