# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: devopsdockeruh/coursepage:latest
